{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRole }}
  labels:
    app.kubernetes.io/name: {{ include "leader-election-operator.name" . }}
    helm.sh/chart: {{ include "leader-election-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "sample.operator.javaoperatorsdk.io"
    resources:
      - leaderelections
      - leaderelections/status
    verbs:
      - '*'
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - '*'
{{- end }}