apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "leader-election-webhook.name" . }}
    helm.sh/chart: {{ include "leader-election-webhook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: leader-election-webhook
  template:
    metadata:
      labels:
        app: leader-election-webhook
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--tls-cert-file=/etc/webhook/certs/tls.crt"
            - "--tls-key-file=/etc/webhook/certs/tls.key"
            - "--port={{ .Values.service.targetPort }}"
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.tls.secretName }}